### ISSUE TITLE
Unvalid route redirect after deleting a post: "Uncaught That named route does not exist!"

### ISSUE THREAD

**Issue by roelvan** [SachaG/Microscope#1]

**Comment by tmeasday** [comment]
Hi @roelvan. Thanks for the bug report!

I can't reproduce this. Can you tell me what commit you were running against?

**Comment by roelvan** [comment]
@tmeasday, I just tested it on the online demo, but I have the same issue on my local latest clone. I added a video to show you the problem: http://db.tt/BWYoefz9

(Problem with the post-edit.js router redirect)

**Comment by tmeasday** [comment]
Hi @roelvan -- are you saying it worked OK on the online demo?

The error implies that you've not defined the `'postsList'` route. Perhaps you mis-typed it?
